### ISSUE TITLE
Add in the documentation how to create robots.txt and sitemap

### ISSUE THREAD

**Issue by tanrax** [tonyaldon/one.el#6]
It's just a suggestion.

## Add robots.txt

Make `assets/robots.txt` with this content:

```
User-Agent: *
Allow: /
Sitemap: https://domain.com/sitemap.txt
```

## Add sitemap

You can create a simple sitemap in txt. [Check this link](https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap?hl=es#text)

Only add in `onerc.el`

``` elisp
(defvar domain "example.com")

(defun make-sitemap (pages tree global)
  "Produce file ./public/sitemap.txt"
  (with-temp-file "./public/sitemap.txt"
    (insert
     (mapconcat 'identity (mapcar
			   (lambda (page)
			     (let* ((path (plist-get page :one-path))
				    (link (concat "https://" domain path)))
			       link
			       ))
			   pages) "\n"))))

(add-hook 'one-hook 'make-sitemap)
```

**Comment by tonyaldon** [comment]
Thanks @tanrax for the suggestion with code snippet.

I've just added it to the documentation in the 'Miscellaneous' section and also gives you the credit (I hope this is OK for you):

https://one.tonyaldon.com/docs/miscellaneous/

I just incoporated the `https` protocol in the `domain` variable, so that people can just change it for `http` if they need without changing `make-sitemap` function.
